### ISSUE TITLE
Question about usePagination

### ISSUE THREAD

**Issue by KishiTheMechanic** [beautifulife/beautifulife-relay-app-example#1]
Hello, thank you for publish this application example.
I'm also using relay-hooks version 4.x and I can't handle usePagination() hook well.
I feel like the loadNext function returns always same cursor.

I saw you commented out this component and I guess you have same problem.
Is it correct?
https://github.com/beautifulife/beautifulife-relay-app-example/blob/master/src/components/TodoListPaginated.tsx

Sorry for suddenly question.
Thank you for your time.
Happy coding!

**Comment by beautifulife** [comment]
@KishiTheMechanic 

Oh hi! 

As you said i use usePagination hook. 
but i have never experienced that problem (always same cursor). 

can you show me your project ?? 
In my opinion, if your code is same as mine. it might be server problem, i guess.

Anyway, feel free to ask me :)

**Comment by KishiTheMechanic** [comment]
Thank you for your reply and sorry for late response.
As you said, that was backend server problem.
My server made by Nexus GraphQL framework had returned wrong cursor and that's the problem I had.
Thank you so much again.

Happy coding!
